fix: migrate to hertzner deployment
Signed-off-by: Lens <yoanyombapro@gmail.com>

diff --git a/.github/workflows/reusable-k8s-deployment.yml b/.github/workflows/reusable-k8s-deployment.yml
--- a/.github/workflows/reusable-k8s-deployment.yml
+++ b/.github/workflows/reusable-k8s-deployment.yml
@@ -139,7 +139,8 @@ jobs:
           HELM_CMD="helm"
           RELEASE_STATUS=$(helm status ${{ inputs.release_name }} -n ${{ inputs.namespace }}  --insecure-skip-tls-verify --kube-insecure-skip-tls-verify 2>&1 || true)
 
-          if echo "$RELEASE_STATUS" | grep -q "not found"; then
+          # Check if the release doesn't exist or has no deployed releases
+          if echo "$RELEASE_STATUS" | grep -q "not found" || echo "$RELEASE_STATUS" | grep -q "has no deployed releases"; then
             echo "🚀 Performing fresh installation..."
             HELM_CMD="$HELM_CMD install ${{ inputs.release_name }}"
           else
